class ValidatorError(Exception):
    pass

class RepoError(Exception):
    pass